### ISSUE TITLE
Release of Code

### ISSUE THREAD

**Issue by ibaranov-cp** [NicksSimulationsROS/multi_jackal#1]
Hey @Nick-Sullivan !
Got your email.
Of course, this is totally fine to do.

I might even suggest for @tonybaltovski to chime in on possiblity of rolling this into the standard Jackal Repo.

Good stuff!

**Comment by Nick-Sullivan** [comment]
Thanks!
The ROS doco is up: http://wiki.ros.org/multi_jackal_tutorials
